# Generated by Django 4.0.6 on 2022-07-30 02:10

from django.db import migrations, models
import usermanagement.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=20)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to=usermanagement.models.upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='User_custom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
    ]
